{
 "title": "Graphcast POI Radio",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Comparison Results",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "constant": 6.5,
     "dataPath": "data",
     "endTimePath": "endTime",
     "groupBy": "resultType",
     "queryText": "query {\n  data:comparisonResults{\n    deployment\n    resultType\n  }\n}",
     "timePath": "Time"
    }
   ]
  },
  {
   "title": "Message averages",
   "type": "bargauge",
   "description": "Average metrics based on each scrape\n- counter for received valid messages\n- gauge of cached messages\n\n- cached messages \n",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "constant": 6.5,
     "dataPath": "data",
     "endTimePath": "endTime",
     "expr": "avg(graphcast_poi_radio_validated_messages{})",
     "queryText": "query {\n      data:submissions(user:\"$user\"){\n          Time:submitTime\n          idle running completed\n      }\n}",
     "timePath": "Time"
    },
    {
     "expr": "avg(graphcast_poi_radio_cached_messages{})"
    },
    {
     "expr": "avg(graphcast_poi_radio_local_npois_to_compare{})"
    }
   ]
  },
  {
   "title": "Result Aggregation",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "constant": 6.5,
     "dataPath": "data",
     "endTimePath": "endTime",
     "groupBy": "null",
     "queryText": "query {\n  data:comparisonRatio{\n    deployment\n    blockNumber\n    senderRatio\n    stakeRatio\n  }\n}",
     "timePath": "Time"
    }
   ]
  },
  {
   "title": "Indexer count by NPOI",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(graphcast_poi_radio_indexer_count_by_npoi_bucket[5m])) by (le))"
    },
    {
     "expr": "rate(graphcast_poi_radio_indexer_count_by_npoi_count[1m])"
    },
    {
     "expr": "graphcast_poi_radio_indexer_count_by_npoi"
    }
   ]
  },
  {
   "title": "Locally tracked NPOIs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "graphcast_poi_radio_local_npois_to_compare"
    }
   ]
  },
  {
   "title": "Number of active peer indexers",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "graphcast_poi_radio_ACTIVE_INDEXERS"
    }
   ]
  },
  {
   "title": "Rate of receiving messages",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "rate(graphcast_poi_radio_validated_messages[5m])"
    },
    {
     "expr": "rate(graphcast_poi_radio_cached_messages[5m])"
    }
   ]
  },
  {
   "title": "Number of diverged subgraphs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "graphcast_poi_radio_diverging_subgraphs"
    }
   ]
  },
  {
   "title": "Function Stats",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "targets": [
    { "expr": "function_calls_concurrent" },
    {
     "expr": "histogram_quantile(0.95, sum(rate(function_calls_duration_bucket[5m])) by (le))"
    },
    { "expr": "rate(function_calls_count[5m])" }
   ]
  },
  { "type": "welcome", "gridPos": { "h": 3, "w": 24, "x": 0, "y": 40 } },
  { "type": "gettingstarted", "gridPos": { "h": 9, "w": 24, "x": 0, "y": 43 } },
  { "title": "Dashboards", "type": "dashlist", "gridPos": { "h": 15, "w": 12, "x": 0, "y": 52 } },
  { "title": "Latest from the blog", "type": "news", "gridPos": { "h": 15, "w": 12, "x": 12, "y": 52 } }
 ]
}